name:                conduit-server
version:             0.1.0.0
github:              uliSchuster/real-world-backend
license:             Apache-2.0
author:              Ulrich Schuster
maintainer:          real-world-study-group@ugsmail.mailworks.org
copyright:           2020 Ulrich Schuster

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A backend according to the http://realworld.io/ spec.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/uliSchuster/real-world-backend#readme>

dependencies:
- base
- rio
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fwarn-tabs

executables:
  conduit-server-exe:
    main:                Main.hs
    source-dirs:         conduit-server
    dependencies:
    - postgresql-simple
    - aeson
    - aeson-pretty
    - conduit-domain
    - conduit-usecases
    - conduit-persistence
    - conduit-interactor
    - conduit-presenter

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

