name:                real-world-server
version:             0.1.0.0
github:              uliSchuster/real-world-backend
license:             Apache-2.0
author:              Ulrich Schuster, Mona Lux
maintainer:          real-world-study-group@ugsmail.mailworks.org
copyright:           2020 Ulrich Schuster, Mona Lux

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A backend according to the http://realworld.io/ spec.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/uliSchuster/real-world-backend#readme>

dependencies:
- base >= 4.11 && < 10
- rio
- email-validate
- modern-uri
- time
- tasty
- tasty-hunit
- tasty-quickcheck
- tasty-discover
- QuickCheck
- quickcheck-instances
- quickcheck-text
- checkers
- text-latin1
- profunctors
- product-profunctors
- postgresql-simple
- opaleye
- optparse-applicative
- aeson
- aeson-pretty
- errors

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  real-world-server-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - real-world-server
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  real-world-server-test:
    main:                Test.hs
    source-dirs:         test
    dependencies:
    - real-world-server
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-discover
    - QuickCheck
    - quickcheck-instances
    - quickcheck-text
    - checkers

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
