name:                conduit-presenter
version:             0.1.0.0
github:              uliSchuster/real-world-backend
license:             Apache-2.0
author:              Ulrich Schuster
maintainer:          real-world-study-group@ugsmail.mailworks.org
copyright:           2020 Ulrich Schuster

# Metadata used when publishing your package
# synopsis:            Presentation types and logic for the Conduit application
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/uliSchuster/real-world-backend#readme>

dependencies:
- base >= 4.11 && < 10
- rio
- email-validate
- modern-uri
- time
- tasty
- tasty-hunit
- tasty-quickcheck
- tasty-discover
- QuickCheck
- quickcheck-instances
- quickcheck-text
- text-latin1
- errors
- either
- aeson
- aeson-pretty

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fwarn-tabs

library:
  source-dirs:
  - src
  dependencies:
  - conduit-domain
  - conduit-usecases
